### ISSUE TITLE
Not support on iOS 16.0

### ISSUE THREAD

**Issue by ankitpanchotiya99138** [JamesSedlacek/Routing#32]
As per the documentation Routing support iOS 16.0 version as well but after new update it's not.

**Comment by JamesSedlacek** [comment]
It supports iOS 16.0

You just need to make a `Router` that conforms to `RoutableObject` & uses the `ObservableObject` protocol + `@Published` properties instead of the `@Observable` macro.

**Comment by JamesSedlacek** [comment]
```swift
public final class Router<Routes: Routable>: RoutableObject, ObservableObject {
    public typealias Destination = Routes

    @Published public var stack: [Routes] = []

    public init() {}
}
```

Something like this
