### ISSUE TITLE
After Updating the package 

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [JamesSedlacek/Routing#33]
Hello JamesSedlacek,

After upgrading the package today, I have encountered the following error message whenever the Routing module is being utilized:

`Router is only available in iOS 17.0 or newer.`

I kindly request your prompt attention to this matter. Thank you for your assistance in resolving this issue as soon as possible

Thank you.

**Comment by JamesSedlacek** [comment]
https://github.com/JamesSedlacek/Routing/issues/32
