### ISSUE TITLE
NavigationStack With TabBar

### ISSUE THREAD

**Issue by zardasht-jazaa** [JamesSedlacek/Routing#34]
Hello,  I have an issue with my TabBar, when I wrap my HomeView , that contain an tabBar , and inside the TabBar there is another View for each tab , one of them contain an navigation code , when I am navigating my tabBar disappear , I figured out  , that the issue with the RoutingView Wrapper , how I can fix that?

**Comment by JamesSedlacek** [comment]
TabViews cannot be wrapped with NavigationStack in SwiftUI.
