### ISSUE TITLE
Why My Initialization is always calling ?

### ISSUE THREAD

**Issue by zardasht-jazaa** [JamesSedlacek/Routing#37]
`
       @ AppStorage(AppStorageKeys.localIdentifier.rawValue) var localIdentifier = "en"
       @ ObservedObject var newsViewModel: NewsViewModel
       let category: String
       let language: String
    
    
    init(category: String,
         newsViewModel: NewsViewModel,
         language: String) {
        self.category = category
        self.language = language
        self.newsViewModel = newsViewModel
        newsViewModel.getNews(pagination: true,category: category)
    }
    
`

inside the getNews function I have an print statement when ever the api request called,  so the print state meant Is calling infinitely , what is the reason for that ?

this is how I came to that View 

` 
enum RouteTree: Routable {
case .sectionView(let category, let newsViewModel, let language):
SectionView(category: category, newsViewModel: newsViewModel, language: language)
 .navigationBarBackButtonHidden(true)
`

![Screenshot 2024-04-01 at 1 20 33 AM](https://github.com/JamesSedlacek/Routing/assets/141743367/df7e419a-f513-4098-be56-94859abdc7ed)

**Comment by JamesSedlacek** [comment]
You shouldn't call a function inside of an initializer.
I'd recommend calling it inside of `onAppear` or `task` if it's an async function.
I also don't think it makes sense to pass a `ViewModel` via the initializer.
You can inject an observable object into the View's environment.
