### ISSUE TITLE
onDismiss Handler for Sheets & FullScreenCovers

### ISSUE THREAD

**Issue by JamesSedlacek** [JamesSedlacek/Routing#8]
This would add the ability to write an onDismiss completion handler closure for sheets and fullScreenCovers.

https://developer.apple.com/documentation/swiftui/view/sheet(ispresented:ondismiss:content:)

The sheet view modifier has an optional `onDismiss` closure that we want the ability to use.

Usage Example:
```swift
router.sheet(.settings, onDismiss: {
    print("Sheet dismissed!")
})

router.sheet(.settings) {
    print("Sheet dismissed!")
}

router.fullScreenCover(.settings, onDismiss: {
    print("FullScreenCover dismissed!")
})

router.fullScreenCover(.settings) {
    print("FullScreenCover dismissed!")
}
```

**Comment by afathe7090** [comment]
please, check Pull Requests for this issue.
 @JamesSedlacek
